### ISSUE TITLE
Exchange data between interceptors in interceptor chain

### ISSUE THREAD

**Issue by schlegel11** [mtamme/NProxy#3]
Hi,

would it be possible to exchange data between interceptor calls?
Something like:
...
return invocationContext.Proceed(object data) or (params object[] data)
...
So I can get my type of data in the next interceptor included in the chain:
...
public object Intercept(IInvocationContext invocationContext){
var myData = invocationContext.Data;
}

So for me it would be a nice feature ;)
Anyway great proxy so far the best I've used with C# :)

**Comment by mtamme** [comment]
Hi Marcel,

I would prefer the following solution:

public interface IInvocationContext {

     object Data { get; set; }

     ...

}

so you can do the following in your interceptors:

public object Intercept(IInvocationContext invocationContext)
{
     invocationContext.Data = "My data";

     ...

     return invocationContext.Proceed();
}

public object Intercept(IInvocationContext invocationContext)
{
     var data = invocationContext.Data as string;

     ...

     return invocationContext.Proceed();
}

I can't tell you when I have time to implement the feature. Maybe on a 
rainy weekend since I have to setup VS first :)

Cheers,
Martin

**Comment by schlegel11** [comment]
Hi Martin,

Ah yep of course a setter is a good idea :)
Its not urgent so take your time.
I'm looking forward for the implementation :+1: 
Thank you Martin

**Comment by mtamme** [comment]
Hi Marcel,

I've released version 2.3.5 which includes the mentioned Data property.

Cheers,
Martin

**Comment by schlegel11** [comment]
Awesome :+1: 
Thank you martin :)

Greetings
Marcel
